"use strict";

const base = require('./base');
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _xRecommended = _interopRequireDefault(require("./4-x-recommended.js"));
var _a11y = _interopRequireDefault(require("./a11y.js"));
var _recommended = _interopRequireDefault(require("./recommended.js"));
var _stylistic = _interopRequireDefault(require("./stylistic.js"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
// STOP: This file is autogenerated by: npm run update:indices
var _default = {
  '4-x-recommended': _xRecommended.default,
  a11y: _a11y.default,
  recommended: _recommended.default,
  stylistic: _stylistic.default
};

for (const [k, b] of Object.entries(_default)) {
  const overrides = base.overrides.concat(b.overrides || []);
  _default[k] = { ...base, ...b, ...{ overrides } };
  for (const [name, conf] of Object.entries(_default[k].rules)) {
    _default[k].rules[`ember-template-lint/${name}`] = conf;
    delete _default[k].rules[name];
  }
}


exports.default = _default;
module.exports = exports.default;